// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlFJIkKNTtmcVfbHE3X0hzV1knyh0s1g',
    appId: '1:734835239685:web:4b53d503c195f36145656c',
    messagingSenderId: '734835239685',
    projectId: 'loginsetup-96640',
    authDomain: 'loginsetup-96640.firebaseapp.com',
    storageBucket: 'loginsetup-96640.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnBb1Owblfwfs0Hz1qem1e9KlglOZDpZw',
    appId: '1:734835239685:android:a5740073c73d39da45656c',
    messagingSenderId: '734835239685',
    projectId: 'loginsetup-96640',
    storageBucket: 'loginsetup-96640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCp4WSk3N07gw37Aik1_c-z1Kww4uvGg',
    appId: '1:734835239685:ios:f182fdfbafdac7b945656c',
    messagingSenderId: '734835239685',
    projectId: 'loginsetup-96640',
    storageBucket: 'loginsetup-96640.firebasestorage.app',
    iosBundleId: 'com.example.loginsetup',
  );
}
